manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: HyeongGeunPark
      url-base: https://github.com/HyeongGeunPark
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: HyeongGeunPark
      revision: 5c455291e35519283c3bf8cfcf42770338eab457

  self:
    path: config
