on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
